$ANSIBLE_VAULT;1.1;AES256
62333434353538633164333336633934623734633166316264616261313964633164326230373332
6534663236623634666139313963303065346231613464650a346362323864383962323362326232
33363365663565326562303034663463326634326435393134663431393461326564326330613631
3763386263336539650a666162326430383436383866646566323064643538353735396232376566
37643662373563333739383533633161313861646235613565663133353938666334353663353464
38356162376339313939333030346433353135633836383439623265633066363266393235633538
393535313433326635643535303163613638
