$ANSIBLE_VAULT;1.1;AES256
31316632383735616463646564623932383631336632343539353362303230313332656134306338
6432633162663239653630643136323964313033633331620a303238386133643830306135636364
36363165323538663539396630393561353436653961383032373835306634363337666262383131
3065343665393763350a626135633330373764326166663733623038393162613065396138343666
30643431633430623437353933356163626533333738653137343732633937383735306433653938
66613438663063333263323737313333343033663436316164623033633231626430376463396164
66336266356262623132613563353338633530653935343330636561663962323061326165646166
35363233653737343665616161356531663461313539633032626135623163643234613963303830
35393364346262626331663765663064393066366239336631656531383962386466363865313461
3062343636346639323266656561373833333331333730663833
